server:
  port: 8081

spring:
  application:
    name: 01-provider-8081

  jpa:
    # \u6307\u5B9A\u662F\u5426\u5728spring\u5BB9\u5668\u542F\u52A8\u7684\u65F6\u5019\u521B\u5EFA\u8868\uFF0C\u9ED8\u8BA4\u4E3AFALSE\uFF0C\u6539\u4E3ATure
    generate-ddl: true
    # \u6307\u5B9A\u5E94\u7528\u91CD\u542F\u65F6\u5019\u4E0D\u66F4\u65B0\u8868
    hibernate:
      ddl-auto: update
    # \u6307\u5B9A\u5728\u63A7\u5236\u53F0\u5C55\u793ASQL
    show-sql: true

  #\u914D\u7F6E\u6570\u636E\u5E93
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://192.168.0.188:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: "123456"

# \u914D\u7F6E\u65E5\u5FD7
logging:
  #\u63A7\u5236\u53F0\u65E5\u5FD7\u7684\u8F93\u51FA\u683C\u5F0F
  pattern:
    console: level-%level %msg%n
  #\u663E\u793A\u65E5\u5FD7\u6253\u5370\u7EA7\u522B
  level:
    root: info
    org.hibernate: info




