server:
  port: 8081

#微服务名称
spring:
  application:
    name: depart-provider

  #nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

 #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://192.168.0.188:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: "123456"


logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info




